name: Coins
version: '1.0-SNAPSHOT'
main: me.darkwinged.coins.Coins
api-version: '1.21'
commands:
  balance:
    description: Checks the amount of coins a player has
    aliases:
      - coins
      - bal
  economy:
    description: The admin side of things